# Azure Authentication

name: Run Azure Login with OpenID Connect
on:
  workflow_dispatch:

permissions:
  id-token: write # Require write permission to Fetch an OIDC token.
      
jobs: 
  Authentication:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION01_ID }} 
        enable-AzPSSession: true

    - name: Azure PowerShell script
      uses: azure/powershell@v2
      with:
        azPSVersion: latest
        inlineScript: |
          Get-AzContext  
          # You can write your Azure PowerShell inline scripts here.